### ISSUE TITLE
Axis PTZ cam with onvif 1.2 error: The requested profile token ProfileToken does not exist

### ISSUE THREAD

**Issue by mjansens** [ltoscano/ponvif#2]
Hi, Im' trying to control an Axis P5534 PTZ IP camera.

The test_v11.php script works at the beginning initialize() and getSources()  are ok.
But the media_GetStreamUri($profileToken) call returns the error 'The requested profile token ProfileToken does not exist' (is $test['lastresponse']['Envelope']['Body']['Fault']['Detail']['Text'])
The profile token is 'quality h264' but the camera's web interface lists the profile name as 'quality' 
Any idea what could go wrong here?
Maybe the space in the string is causing problems?
I tried calling the method with just 'quality', but still the same error.

The camera says it supports Onvif 1.2

Thanks for any help.
Michel

**Comment by mjansens** [comment]
Hi,

I found the solution: I had to replace the space with an underscore... 
I don't know if it is general to cameras though...

Michel

**Comment by ltoscano** [comment]
Hi Michel,
good job.
Sorry for the delay.
Regards
Lorenzo

Il giorno 17 nov 2015, alle ore 13:55, mjansens notifications@github.com ha scritto:

Hi,

I found the solution: I had to replace the space with an underscore... 
I don't know if it is general to cameras though...

Michel
